version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      - mysql  # Ensure MySQL starts before the app

  mysql:
    image: mysql:latest
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"  # MySQL container runs on 3306, but accessible via 3307 on host
    networks:
      - my-network  # Ensure both app and mysql are in the same network

networks:
  my-network:
    driver: bridge  # Custom network for the containers
